# Generated by Django 5.0.6 on 2024-06-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
